### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [raphaelriet/0.5.1.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

https://github.com/raphaelriet/0.5.1.1/blob/4bff2a24e4aab08f837d5e9b74b907e7842d0b2c/index.html#L13-L17

Tudo ok com a implementação, so tem um problema de funcionalidade: os links para os status deveriam estar visíveis em todas as paginas. O seu botão de voltar não seria necessário se voce exibisse o seu `nav` em todos eles. Por conta disso, faltou implementar uma funcionalidade que é o destaque de qual status esta sendo listado. Você poderia alcançar essa funcionalidade criando uma classe `ativo` e usando ela na página aproprieda. Veja o exemplo abaixo de como seria no `.html` do `excluidos.html`.

```html
<nav>
  <a href="pendentes.html" class="pendentes">Pendentes</a>
  <a href="concluidos.html" class="concluidos">Concluídos</a>
  <a href="excluidos.html" class="ativo excluidos">Excluídos</a>
</nav>
```

**Nota:** 9

# Comentários

Notei que muitas das suas propriedades CSS são duplicadas entre as classes `pendentes` `concluidos` e `excluidos`. Você poderia criar uma classe mais genérica para armazenar essas propriedades e então fazer uso de duas classes. Veja no exemplo abaixo que é utilizada a classe `tarefa` junto com a classe `pendentes`. 

```html
<a class="tarefa pendentes" href="/pendentes.html">Pendentes</a>
``` 

O CSS ficaria assim: 

```css
.tarefa {
    margin: 10px;
    padding: 10px;
    border: 1px solid #8fd14f;
    border-radius: 5px;
    color: white;
}

.pendentes {
    background: #8fd14f;
}

.concluidos {
    background: #0ca789;
}

.excluidos {
    background: #eb4045;
}
```

Você pode imaginar agora que `tarefa` possui três subvariações: `pendente`, `concluido` e `excluido`.

```mermaid
flowchart LR;
  tarefa --> concluido;
  tarefa --> pendente;
  tarefa --> excluido;
```
